[package]
name = "modda"
version = "1.7.2-pre3"
authors = ["Mickaël <mleduque@gmail.com>"]
description = "Weidu install automation"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.79"
bytes = "1.5.0"
clap = "4.4.12"
clap_derive = "4.4.7"
directories = "5.0.1"
chardetng = "0.1.17"
chrono = "0.4.31"
dialoguer = "0.11.0"
encoding_rs = "0.8.33"
env_logger = "0.11.1"
filetime = "0.2.23"
flate2 = "1.0.28"
fs_extra = "1.3.0"
futures-util = "0.3.30"
globwalk = "0.9.0"
handlebars = "5.0.0"
humantime = "2.1.0"
indicatif = "0.17.7"
indoc ="2.0.4"
itertools = "0.12.0"
lazy_static = "1.4.0"
log = "0.4.20"
patch = { path = "../patch-rs" }
path-clean = "1.0.1"
path-absolutize = "3.1.1"
percent-encoding = "2.3.1"
regex = "1.10.2"
reqwest = { version = "0.11.23", default-features = false, features = ["stream", "json", "rustls-tls-native-roots"] }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
serde_path_to_error = "0.1.15"
serde_with = "3.4.0"
serde_yaml = "0.9.30"
shellexpand = "3.1.0"
tar = "0.4.40"
tokio = { version = "1.35.1", features = ["full"] }
tempfile = "3.9.0"
url = "2.5.0"
zip = "0.6.6"
void = "1.0.2"

[dev-dependencies]
faux = "0.1.9"
function_name = "0.3.0"
