name: build

on:
  push:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          #- x86_64-pc-windows-gnu
          #- x86_64-apple-darwin

    runs-on: ubuntu-latest

    steps:
    # checkout
    - uses: actions/checkout@v3
    # set up rust cache
    - uses: Swatinem/rust-cache@v2
    # build
    - name: Build
      run: cargo build --verbose
    # tests
    - name: Run tests
      run: cargo test --verbose
